# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the entropy for the current cluster weights.
#' 
#' @param class_weights The vector of the cluster weights from a mixture model.
#' 
#' @return The information entropy for the current cluster weights.
calcEntropy <- function(class_weights) {
    .Call('_tagmmdi_calcEntropy', PACKAGE = 'tagmmdi', class_weights)
}

#' Updates the concentration parameter in the Dirichlet distribution.
#' 
#' @param concentraiton_0 The prior on the concentration parameter.
#' @param cluster_labels The current labelling.
#' @param n_cat The number of categories / clusters.
#' @param count_from 0 or 1; number to start labelling from (R uses 1, C++ 0).
#' 
#' @return Updated concentration vector based on current observations.
NULL

#' Counts the number of unique entries in a vector v.
#' 
#' @param v Vector of discrete labels.
#' 
#' @return Count of the number of unique labels in v.
NULL

#' Sample the cluster membership of point from the categorical distribution.
#' 
#' @param point A row from the dataset corresponding to the measurements for a 
#' given sample.
#' @param data Matrix of categorical data.
#' @param class_probabilities Field of matrices (one for each variable) of 
#' category probabilities within each cluster.
#' @param cluster_weights Vector of cluster weights.
#' @param n_clust The number of clusters present.
#' @param n_col The number of columns / variables in data.
#' 
#' @return Vector of cluster assignment probabilities for a given sample.
NULL

#' Returns a vector of the number of unqiue values in each column of data.
#' 
#' @param data Matrix of categorical data.
#' 
#' @return Vector of counts of the number of categories in each variable in data.
countCategories <- function(data) {
    .Call('_tagmmdi_countCategories', PACKAGE = 'tagmmdi', data)
}

#' Finds the number of categories in each covariate and declares the appropriate
#' matrix to record the associated probabilties for each cluster.
#' 
#' @param cat_count Number of categories present in each variables.
#' @param n_col Number of variables.
#' @param n_clust Number of clusters present.
#' 
#' @return Field of matrices (must be a field as matrices are not always the
#' same dimension), where each matrix is associated with a single variable and
#' holds the probabilities of each category within the variable for the n_clust
#' clusters.
declareClassProbsField <- function(cat_count, n_col, n_clust) {
    .Call('_tagmmdi_declareClassProbsField', PACKAGE = 'tagmmdi', cat_count, n_col, n_clust)
}

#' Sample parameters for a dirichlet distribution (normally for the clusters).
#' 
#' @param concentration_0 Pior on the concentration parameter.
#' @param cluster_labels Current clustering.
#' @param n_clusters The number of clusters present.
#' @param count_from 0 or 1; to allow for C++ or R counting.
#' 
#' @return Vector sampled from Dirichlet posterior.
sampleDirichletPosterior <- function(concentration_0, cluster_labels, n_clusters, count_from) {
    .Call('_tagmmdi_sampleDirichletPosterior', PACKAGE = 'tagmmdi', concentration_0, cluster_labels, n_clusters, count_from)
}

#' Sample the probabilities for each category across all clusters for each 
#' covariate
#' 
#' @param data Matrix of categorical data
#' @param class_probs Field of matrices (one for each variable) of category
#' probability for each cluster.
#' @param phi_prior Prior on class_probs.
#' @param cluster_labels Current labelling within dataset.
#' @param cat_count Vector of the number of categories within each variable.
#' @param n_clust The number of clusters present.
#' @param n_col The number of variables present.
#' @param class_start 0 or 1; allows labelling to begin at 0 or 1 (C++ 
#' convention versus that of R).
#' 
#' @return Field of matrices of sampled class weights for each cluster within 
#' each variable.
sampleCategoryProbabilities <- function(data, class_probs, phi_prior, cluster_labels, cat_count, n_clust, n_col, class_start) {
    .Call('_tagmmdi_sampleCategoryProbabilities', PACKAGE = 'tagmmdi', data, class_probs, phi_prior, cluster_labels, cat_count, n_clust, n_col, class_start)
}

sampleCategoricalDistn <- function(point, data, class_probabilities, cluster_weights, n_clust, n_col) {
    .Call('_tagmmdi_sampleCategoricalDistn', PACKAGE = 'tagmmdi', point, data, class_probabilities, cluster_weights, n_clust, n_col)
}

categoricalClustering <- function(data, phi_prior, cluster_labels, fix_vec, cluster_weight_priors, num_clusters, num_iter, burn, thinning) {
    .Call('_tagmmdi_categoricalClustering', PACKAGE = 'tagmmdi', data, phi_prior, cluster_labels, fix_vec, cluster_weight_priors, num_clusters, num_iter, burn, thinning)
}

#' Converts a vector of log, unnormalised probabilities to probabilities.
#' @param my_log_vec A vector of log, unnormalised porbabilities.
#' 
#' @return The exponentiated, normalised transform of my_log_vec.
NULL

#' @param prob_vec Vector of cluster assignment probabilities.
#' @param start_label The value clusters are counted from (typcially 0 in C++ 
#' and 1 in R).
NULL

#' Predicts cluster membership.
#' 
#' @param prob_vec Vector of cluster assignment scores (unnormalised, log 
#' probabilities).
#' @param start_label The value clusters are counted from (typcially 0 in C++ 
#' and 1 in R).
#' @return Label representing predicted cluster membership.
NULL

#' Returns the normal distribution log-likelihood.
#' 
#' @param point Column vector describing the measurements for a sample of data.
#' @param mu The mean for the data (same dimensionality as point).
#' @param variance The covariance matrix.
#' @param d The dimensionality of point.
#' 
#' @return The log likelihood of the multivariate normal distribution for an
#' observation.
NULL

#' For k classes returns a k-vector of probabilities for point to belong to said
#' classes.
#' 
#' @param point The column vector of measurements for a given sample.
#' @param data A matrix of the entire dataset.
#' @param k The number of clusters present.
#' @param class_weights The k-vector of cluster weights.
#' @param mu d x k matrix of mean vectors for each cluster.
#' @param variance k-cube of d x d covariance matrices for each cluster.
NULL

gaussianClustering <- function(num_iter, concentration_0, scale_0, class_labels, fix_vec, mu_0, lambda_0, data, nu_0, k, burn, thinning, outlier = FALSE, t_df = 4.0, normalise = FALSE, u = 2, v = 10) {
    .Call('_tagmmdi_gaussianClustering', PACKAGE = 'tagmmdi', num_iter, concentration_0, scale_0, class_labels, fix_vec, mu_0, lambda_0, data, nu_0, k, burn, thinning, outlier, t_df, normalise, u, v)
}

#' Returns a variable involved in updating the scale, it is similar to sample 
#' covariance
#' 
#' @param data Data in matrix format
#' @param sample_mean Sample mean for data
#' @param n The number of samples in data
#' @param n_col The number of columns in data
#' 
#' @return One of the parameters required to calculate the posterior of the
#'  Multivariate normal with uknown mean and covariance (the unnormalised 
#'  sample covariance).
NULL

#' Returns a vector of the mean of a cluster of size n
#' 
#' @param lambda_0 The prior on the shrinkage of the variance estimated from 
#' the Inverse Wishart as the variance of the mean parameter.
#' @param mu_0 The prior on the mean.
#' @param n The number of samples in the pertinent dataset.
#' @param n_col The number of columns in the pertinent dataset.
#' @param sample_mean The sample mean of the pertinent dataset.
#' 
#' @return The updated values of the mean parameter for the Multivariate Normal.
NULL

#' @param scale_0 The prior on the scale parameter of the Inverse Wishart 
#' distribution.
#' @param sample_cov The sample covariance of the pertinent dataset.
#' @param lambda The prior on the shrinkage of the variance.
#' @param n The number of pobservations in the pertinent dataset.
#' @param sample_mean The sample mean from the pertinent dataset.
#' @param mu_0 The prior on the mean parameter.
#' @param d The number of columns in the dataset used.
#' 
#' @return The updated scale parameter.
NULL

#' Function to sample a nxn covariance matrix from the inverse wishart for given 
#' priors.
#' 
#' @param nu_0 The prior on the nu parameter of the inverse Wishart (must be
#' greater than or equal to the number of columns in the data).
#' @param scale_0 The prior on the scale parameter of the inverse-Wishart.
#' @param lambda The prior on the shrinkage on variance of the Normal 
#' distribution.
#' @param mu_0 The prior on the mean parameter.
#' @param data The dataset updating our belief of the variance.
#' 
#' @return A covariance matrix sampled from the posterior distribution.
NULL

#' Function sampling from the mean posterior.
#' 
#' @param mu_0 Prior on the mean parameter.
#' @param variance The covariance matrix for the Multivariate normal distribution (sampled from the inverse-Wishart).
#' @param lambda_0 Prior on the shrinkage applied to the variance parameter.
#' @param data The data used to update our prior.
#' 
#' @return A mean vector sampled from the posterior distribution.
NULL

#' Returns a 2-D field of cubes (i.e. a 5D object) for the current iterations 
#' means and variances across each cluster (hence a field)
#' 
#' @param data The entrie dataset.
#' @param cluster_labels Binary vector of cluster labels with the ith entry 
#' corresponding to the membership of the ith observation in data.
#' @param k The maximum number of clusters allowed.
#' @param nu_0 The prior on the nu parameter for the inverse-Wishart.
#' @param num_cols The number of columns in data.
#' @param scale_0 The prior on the sclae parameter. A positive definite matrix.
#' @param mu_0 The prior on the mean parameter.
#' 
#' @return A cube of covariance matrices sampled from the posterior 
#' distribution for each cluster within the data.
NULL

#' Returns a matrix of the sampled means for each cluster within the data. The
#' means are column vectors within the outputted matrix.
#' 
#' @param data Matrix of entire dataset.
#' @param cluster_labels Vector of membership labels with entries corresponding 
#' to the data (i.ew. the ith entry is for the observaiton in the ith row of 
#' data).
#' @param k The number of clusters present.
#' @param num_cols The number of columns in the dataset.
#' @param variance A cube of covaraince matrices with that associated with the
#' ith cluster in the ith entry.
#' @param lambda_0 The prior on the shrinkage parameter.
#' @param mu_0 The prior on the mean parameter.
#' 
#' @return A num_cols x k matrix consisting of column vectors of the sampled
#' means for each cluster.
NULL

#' Returns a 2-D field of cubes (i.e. a 5D object) for the current iterations 
#' means and variances across each cluster (hence a field)
#' 
#' @param data Matrix of the data.
#' @param cluster_labels Vector of membership labels with entries corresponding 
#' to the data (i.ew. the ith entry is for the observaiton in the ith row of 
#' data).
#' @param k The number of clusters present.
#' @param nu_0 The prior on the nu parameter for the inverse-Wishart.
#' @param num_cols The number of columns in the dataset.
#' @param @param scale_0 The prior on the sclae parameter. A positive definite matrix.
#' @param lambda_0 The prior on the shrinkage parameter.
#' @param mu_0 The prior on the mean parameter.
#' 
#' @return cube of the mean and covariance sampled from the posterior of each 
#' cluster.
NULL

mdiCatCat <- function(data_1, data_2, class_dist_prior_1, class_dist_prior_2, clust_weight_priors_1, clust_weight_priors_2, clust_labels_1, clust_labels_2, n_clust_1, n_clust_2, fix_vec_1, fix_vec_2, a_0, b_0, num_iter, burn, thinning) {
    .Call('_tagmmdi_mdiCatCat', PACKAGE = 'tagmmdi', data_1, data_2, class_dist_prior_1, class_dist_prior_2, clust_weight_priors_1, clust_weight_priors_2, clust_labels_1, clust_labels_2, n_clust_1, n_clust_2, fix_vec_1, fix_vec_2, a_0, b_0, num_iter, burn, thinning)
}

mdiGaussCat <- function(cont_data, cat_data, mu_0, lambda_0, scale_0, nu_0, a_0, b_0, clust_wgt_priors_gauss, clust_wgt_priors_cat, phi_prior, clust_labels_gauss, clust_labels_cat, n_clust_gauss, n_clust_cat, fix_vec_1, fix_vec_2, n_iter, burn, thin, allow_outliers = FALSE, t_df = 4.0, normalise = FALSE, u_1 = 2, v_1 = 10, rate_gauss_0 = 1L, rate_cat_0 = 1L) {
    .Call('_tagmmdi_mdiGaussCat', PACKAGE = 'tagmmdi', cont_data, cat_data, mu_0, lambda_0, scale_0, nu_0, a_0, b_0, clust_wgt_priors_gauss, clust_wgt_priors_cat, phi_prior, clust_labels_gauss, clust_labels_cat, n_clust_gauss, n_clust_cat, fix_vec_1, fix_vec_2, n_iter, burn, thin, allow_outliers, t_df, normalise, u_1, v_1, rate_gauss_0, rate_cat_0)
}

mdiGaussGauss <- function(data_1, data_2, mu_0_1, lambda_0_1, scale_0_1, df_0_1, mu_0_2, lambda_0_2, scale_0_2, df_0_2, clust_weight_priors_1, clust_weight_priors_2, clust_labels_1, clust_labels_2, n_clust_1, n_clust_2, fix_vec_1, fix_vec_2, a_0, b_0, num_iter, burn, thinning, outlier_1 = FALSE, t_df_1 = 4.0, outlier_2 = FALSE, t_df_2 = 4.0, normalise_1 = FALSE, normalise_2 = FALSE, u_1 = 2, v_1 = 10, u_2 = 2, v_2 = 10, rate_1_0 = 1L, rate_2_0 = 1L) {
    .Call('_tagmmdi_mdiGaussGauss', PACKAGE = 'tagmmdi', data_1, data_2, mu_0_1, lambda_0_1, scale_0_1, df_0_1, mu_0_2, lambda_0_2, scale_0_2, df_0_2, clust_weight_priors_1, clust_weight_priors_2, clust_labels_1, clust_labels_2, n_clust_1, n_clust_2, fix_vec_1, fix_vec_2, a_0, b_0, num_iter, burn, thinning, outlier_1, t_df_1, outlier_2, t_df_2, normalise_1, normalise_2, u_1, v_1, u_2, v_2, rate_1_0, rate_2_0)
}

#' Sample from the posterior of a Gamma distribution.
#' 
#' @param concentration_0 The prior on the concentraion parameter.
#' @param cluster_lables The current clustering.
#' @param k The number of clusters present.
#' @param rate (Default = 1.0) The rate of the gamma distribution.
#' @param count_from The number counting begins at (R = 1, C++ = 0).
#' 
#' @return k-vector of samples from k Gamma distributions.
NULL

#' Calculate the rate for the gamma distribution for the class weights for MDI.
#' This is defined as the sume of the cluster weights (upweighted by the 
#' correlation parameter, phi, if the labels match) multiplied by the variable v.
#' 
#' @param v The strategic latent variable (as in Nieto-Barajas et al., 2004) to 
#' ensure that the posterior of most of the model parameters are Gamma
#' distributions.
#' @param n_clust The number of clusters present.
#' @param cluster_index The current cluster of interest.
#' @param cluster_weights The mixture weights.
#' @param phi The context similarity parameter from MDI; this is a measure of 
#' the similarity of clustering between datasets.
#' 
#' @return The rate for the Gamma distribution to sample the cluster weight from.
NULL

#' Returns the cluster weights for MDI.
#' @param shape_0 The prior on the shape for the cluster weights.
#' @param rate_0 The prior on the rate for the cluster weights.
#' @param v The strategic latent variable (as in Nieto-Barajas et al., 2004) to 
#' ensure that the posterior of most of the model parameters are Gamma
#' distributions.
#' @param n_clust The number of clusters present in the current dataset.
#' @param n_clust_comp The number of clusters present in the other dataset.
#' @param cluster_weights_comp The mixture weights for the other dataset.
#' @param cluster_labels The membership vector for the clustering in the 
#' current dataset.
#' @param cluster_labels_comp The membership vector for the clustering in the 
#' other dataset.
#' @param phi The context similarity parameter from MDI; this is a measure of 
#' the similarity of clustering between datasets.
#' 
#' @return A vector of mixture weights.
NULL

#' Counts the number of samples with the same label in both datasets.
#' 
#' @param cl_1 The vector of membership labels for the first dataset.
#' @param cl_2 The vector of membership labels for the second dataset.
#' @param n The number of samples in each dataset.
#' 
#' @return A count of the number of samples with common labelling in both cl_1
#' and cl_2.
NULL

#' Calculate the factorial of n (i.e. n!).
#' @param n The number to calculate the factorial of.
#' 
#' @return n!
NULL

#' Returns the log of the factorial of n.
#' 
#' @param n The number to calculate the log factorial of.
#' 
#' @return log(n!)
NULL

#' Calculates the t-distribution log likelihood for a given point.
#' 
#' @param point A sample from the dataset.
#' @param mu The mean.
#' @param variance Covariance matrix.
#' @param n_col The length of point.
#' @param df The degrees of freedom variable for a t-distribution.
#' 
#' @return The log-likelihood for a point within a t-distribution.
NULL

#' Samples from a Beta distribution based on the idea that two independent gamma
#' functions can be used. If X ~ Gamma(a, 1) and Y ~ Gamma(b, 1) then
#' X / (X+Y) ~ Beta(a, b). Used in calculating the weights for allocation to 
#' outlier.
#' 
#' @param a Shape parameter of the first gamma distribution.
#' @param b Shape parameter of the second gamma distribution.
#' @param theta (Default = 1.0) Rate of the two Gamma distributions.
#' 
#' @return Sample from Beta(a, b).
NULL

#' Samples if the point is an outlier or not (comparing to assigned class).
#' 
#' @param point A row from the dataset corresponding to the measurements for a 
#' given sample.
#' @param data Matrix of data.
#' @param outlier_weight Weight for outlier assignment.
#' @param gloabl_mean Sample mean of data.
#' @param global_varinace Sample covariance matrix from data.
#' @param t_df (Default = 4.0) Degrees of freedom parameter for the 
#' t-distribution.
#' 
#' @return Probability that current point is an outlier within data.
NULL

#' Calculate the probability of being an outlier or not.
#' @param point A row from the dataset corresponding to the measurements for a 
#' given sample.
#' @param gloabl_mean Sample mean of data.
#' @param global_varinace Sample covariance matrix from data.
#' @param n_col The number of columns present.
#' @param t_df (Default = 4.0) Degrees of freedom parameter for the 
#' t-distribution.
#' @param outlier_weight The weight associated with outlier assignment.
#' @param mu The mean.
#' @param variance Covariance matrix.
#' 
#' @return Vector of non-outlier and outlier assignment probabilities.
NULL

#' Compares how similar two points are with regards to their clustering across 
#' all iterations. Works for unsupervised methods (i.e. allows label flipping).
#' 
#' @param point The index row within cluster_record for the first object.
#' @param comparison_point The comparison row index from cluster_record.
#' @param cluster_record A matrix of combined membership column vectors where 
#' the ijth entry is the membership assigned to the ith person in the jth 
#' iteration of sampling.
#' @param num_iter The number of samples recorded.
#' 
#' @return A score between 0 and 1 of the fraction of iterations for which the 
#' objects denoted by the point and comparison_point rows are assigned the same
#' label.
NULL

#' Constructs a similarity matrix comparing all points clustering across the 
#' iterations.
#' 
#' @param cluster_record Matrix of label assignment for data across iterations.
#' 
#' @return A symmetric n x n matrix (for n rows in cluster record) describing 
#' the fraction of iterations for which each pairwise combination of points are
#' assigned the same label.
createSimilarityMat <- function(cluster_record) {
    .Call('_tagmmdi_createSimilarityMat', PACKAGE = 'tagmmdi', cluster_record)
}

